/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BottleneckRouteImport } from './routes/bottleneck'
import { Route as CommunityDnaRouteImport } from './routes/community-dna'
import { Route as SeedFinderRouteImport } from './routes/seed-finder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BottleneckRoute = BottleneckRouteImport.update({
  id: '/bottleneck',
  path: '/bottleneck',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityDnaRoute = CommunityDnaRouteImport.update({
  id: '/community-dna',
  path: '/community-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedFinderRoute = SeedFinderRouteImport.update({
  id: '/seed-finder',
  path: '/seed-finder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bottleneck': typeof BottleneckRoute
  '/community-dna': typeof CommunityDnaRoute
  '/seed-finder': typeof SeedFinderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bottleneck': typeof BottleneckRoute
  '/community-dna': typeof CommunityDnaRoute
  '/seed-finder': typeof SeedFinderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bottleneck': typeof BottleneckRoute
  '/community-dna': typeof CommunityDnaRoute
  '/seed-finder': typeof SeedFinderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bottleneck' | '/community-dna' | '/seed-finder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bottleneck' | '/community-dna' | '/seed-finder'
  id: '__root__' | '/' | '/bottleneck' | '/community-dna' | '/seed-finder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BottleneckRoute: typeof BottleneckRoute
  CommunityDnaRoute: typeof CommunityDnaRoute
  SeedFinderRoute: typeof SeedFinderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bottleneck': {
      id: '/bottleneck'
      path: '/bottleneck'
      fullPath: '/bottleneck'
      preLoaderRoute: typeof BottleneckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-dna': {
      id: '/community-dna'
      path: '/community-dna'
      fullPath: '/community-dna'
      preLoaderRoute: typeof CommunityDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed-finder': {
      id: '/seed-finder'
      path: '/seed-finder'
      fullPath: '/seed-finder'
      preLoaderRoute: typeof SeedFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BottleneckRoute: BottleneckRoute,
  CommunityDnaRoute: CommunityDnaRoute,
  SeedFinderRoute: SeedFinderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
